import type { CommandContext } from '../../../../platform/engine';
import type { WerewolfCommand } from '../types';

function assertInvalidSystemContext(context: CommandContext): void {
  // @ts-expect-error system commands cannot claim a controlled player seat
  const invalidContext: CommandContext = { ...context, controlledSeat: 1 };
  void invalidContext;
}

function assertInvalidPublicActionFields(validCommand: WerewolfCommand): void {
  // @ts-expect-error actor identity belongs to CommandContext
  const withUserId: WerewolfCommand = { ...validCommand, userId: 'player-1' };
  // @ts-expect-error effective actor seat belongs to CommandContext
  const withSeat: WerewolfCommand = { ...validCommand, seat: 1 };
  // @ts-expect-error role is derived from authoritative state
  const withRole: WerewolfCommand = { ...validCommand, role: 'seer' };
  // @ts-expect-error timestamps are generated by the server
  const withTimestamp: WerewolfCommand = { ...validCommand, timestamp: 100 };
  void [withUserId, withSeat, withRole, withTimestamp];
}

describe('Werewolf command protocol', () => {
  it('keeps actor identity and controlled seat outside commands', () => {
    const command: WerewolfCommand = {
      type: 'werewolf.action.submit',
      input: { kind: 'target', target: 2 },
    };
    const context: CommandContext = {
      actor: { kind: 'user', userId: 'player-1' },
      controlledSeat: null,
      nowMs: 100,
      commandId: 'command-1',
      randomSeed: 'server-seed-1',
    };

    expect(command).toEqual({
      type: 'werewolf.action.submit',
      input: { kind: 'target', target: 2 },
    });
    expect(context.actor).toEqual({ kind: 'user', userId: 'player-1' });
  });

  it('requires a complete system principal and forbids bot control', () => {
    const context: CommandContext = {
      actor: { kind: 'system', effectId: 'effect-1' },
      controlledSeat: null,
      nowMs: 100,
      commandId: 'command-2',
      randomSeed: 'server-seed-2',
    };

    expect(context.actor.kind).toBe('system');
    expect(assertInvalidSystemContext).toBeDefined();
  });

  it('does not accept client-supplied actor, seat, role, or timestamp fields', () => {
    const validCommand: WerewolfCommand = {
      type: 'werewolf.action.submit',
      input: { kind: 'confirm' },
    };

    expect(validCommand.type).toBe('werewolf.action.submit');
    expect(assertInvalidPublicActionFields).toBeDefined();
  });
});
