module.exports = {
  preset: 'jest-expo',
  testTimeout: 10_000,
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|react-native-reanimated|react-native-gesture-handler)',
  ],
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.test.ts', '**/__tests__/**/*.test.tsx'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  collectCoverageFrom: ['src/**/*.{ts,tsx}', '!src/**/*.d.ts'],
  coverageThreshold: {
    global: {
      statements: 60,
      branches: 55,
      functions: 55,
      lines: 60,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  moduleNameMapper: {
    '^@werewolf/game-engine/(.*)$': '<rootDir>/packages/game-engine/src/$1',
    '^@werewolf/game-engine$': '<rootDir>/packages/game-engine/src/index.ts',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^react-native-worklets$': '<rootDir>/__mocks__/react-native-worklets.ts',
    '^expo-audio$': '<rootDir>/__mocks__/expo-audio.ts',
    '^expo-haptics$': '<rootDir>/__mocks__/expo-haptics.ts',
    '^expo-image$': '<rootDir>/__mocks__/expo-image.tsx',
    '^expo-splash-screen$': '<rootDir>/__mocks__/expo-splash-screen.ts',
    '^@expo/vector-icons/(.+)$': '<rootDir>/__mocks__/@expo/vector-icons/$1.tsx',
    '^@expo/vector-icons$': '<rootDir>/__mocks__/@expo/vector-icons/index.tsx',
    '^@sentry/react-native$': '<rootDir>/__mocks__/@sentry/react-native.ts',
    '^@tanstack/react-query$': '<rootDir>/__mocks__/@tanstack/react-query.ts',
    '^sonner-native$': '<rootDir>/__mocks__/sonner-native.ts',
    '^expo-file-system$': '<rootDir>/__mocks__/expo-file-system.ts',
    '^expo-sharing$': '<rootDir>/__mocks__/expo-sharing.ts',
    '^react-native-qrcode-svg$': '<rootDir>/__mocks__/react-native-qrcode-svg.tsx',
    '^react-native-view-shot$': '<rootDir>/__mocks__/react-native-view-shot.ts',
    '^react-native-safe-area-context$': '<rootDir>/__mocks__/react-native-safe-area-context.tsx',
    '^react-native-mmkv$': '<rootDir>/__mocks__/react-native-mmkv.ts',
    '\\.m4a$': '<rootDir>/__mocks__/audioFileMock.js',
  },
};
