/** Public pure Avalon API for transport, persistence and the client game module. */

export { isBotOccupant } from '../../platform/room/seating';
export type { AvalonCommand, AvalonPublicCommand } from './commands/types';
export {
  AVALON_REASONS,
  type AvalonDecision,
  type AvalonEffect,
  type AvalonEvent,
  teamSizeReason,
} from './domain/decision';
export {
  buildAvalonNightInfo,
  getAvalonFailsNeeded,
  getAvalonLadyInitialHolderSeat,
  getAvalonNightParticipants,
  getAvalonQuestSize,
  isAvalonBoardCompositionValid,
  nextAvalonLeaderSeat,
} from './domain/rules';
export {
  type AvalonLadyView,
  type AvalonLastVoteResultView,
  type AvalonQuestHistoryView,
  type AvalonSeatView,
  type AvalonViewModel,
  getAvalonViewModel,
} from './domain/visibility';
export { avalonEngine, decideAvalonCommand, getAvalonLifecycle } from './engine';
export {
  AVALON_STATE_CODEC,
  migratePersistedAvalonState,
  parseAvalonConfig,
  parseAvalonState,
} from './state/codec';
export {
  AVALON_BOARDS,
  AVALON_DEFAULT_VETO_LIMIT,
  AVALON_DEFAULT_VOTE_MODE,
  AVALON_END_REASONS,
  AVALON_FOURTH_QUEST_DOUBLE_FAIL_MIN_PLAYERS,
  AVALON_GAME_TYPE,
  AVALON_LADY_MIN_PLAYERS,
  AVALON_LADY_ROUNDS,
  AVALON_MAX_PLAYERS,
  AVALON_MIN_PLAYERS,
  AVALON_NIGHT_STEPS,
  AVALON_PHASES,
  AVALON_PLAYER_COUNTS,
  AVALON_QUEST_COUNT,
  AVALON_QUEST_ROUNDS,
  AVALON_QUEST_SIZES,
  AVALON_ROLES,
  AVALON_STATE_VERSION,
  AVALON_VETO_LIMIT_MAX,
  AVALON_VETO_LIMIT_MIN,
  AVALON_VOTE_MODES,
  type AvalonAudioEffect,
  type AvalonBallot,
  type AvalonConfig,
  type AvalonEndReason,
  type AvalonHumanSeat,
  type AvalonLadyCheckResult,
  type AvalonLastVoteResult,
  type AvalonNightInfo,
  type AvalonNightStep,
  type AvalonPhase,
  type AvalonPhaseKind,
  type AvalonPlay,
  type AvalonPlayerCount,
  type AvalonQuestHistoryEntry,
  type AvalonQuestRound,
  type AvalonRoleId,
  type AvalonState,
  type AvalonVoteMode,
  DEFAULT_AVALON_CONFIG,
  getAvalonBotDisplayName,
  getAvalonBotSeats,
  getAvalonOccupiedSeatCount,
  getAvalonRealHumanCount,
  getAvalonUserSeat,
  getAvalonViewingParticipants,
  isAvalonBotSeat,
  isAvalonEvilRole,
  isAvalonGoodRole,
  isAvalonOccupiedSeat,
  isAvalonPlayerCount,
  isAvalonQuestRound,
  isAvalonVetoLimit,
  isAvalonVoteMode,
  isValidAvalonConfig,
} from './state/types';
