/**
 * Shared dev-server configuration utilities.
 *
 * Single source of truth for:
 * - Cloudflare wrangler dev helpers (writeDevVars, applyD1Migrations)
 *
 * Consumed by: setup-e2e-api.mjs
 */

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// ─── Constants ───────────────────────────────────────────────────────────────

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ROOT_DIR = join(__dirname, '..', '..');

// ─── writeDevVars ────────────────────────────────────────────────────────────

/**
 * Write a .dev.vars file in the api-worker package for wrangler dev local secrets.
 *
 * wrangler dev reads .dev.vars automatically for secrets (JWT_SECRET, etc.)
 * that aren't in wrangler.toml [vars].
 */
export function writeDevVars() {
  const devVarsPath = join(ROOT_DIR, 'packages', 'api-worker', '.dev.vars');
  const content = [
    '# Auto-generated by setup-e2e-api.mjs — DO NOT COMMIT',
    'JWT_SECRET=e2e-test-jwt-secret-do-not-use-in-production',
    '',
  ].join('\n');
  writeFileSync(devVarsPath, content, 'utf-8');
  console.log('🔑 .dev.vars written (JWT_SECRET for local wrangler dev)');
}

// ─── applyD1Migrations ───────────────────────────────────────────────────────

/**
 * Apply D1 migrations locally via wrangler CLI.
 * Only needed for cloudflare E2E mode — ensures local D1 has the schema.
 *
 * Uses pipe stdio so wrangler detects non-interactive context and auto-confirms.
 */
export function applyD1Migrations() {
  const workerDir = join(ROOT_DIR, 'packages', 'api-worker');
  console.log('🗄️  Applying D1 migrations (local)...');
  try {
    const output = execSync('pnpm run db:migrate:local', {
      cwd: workerDir,
      stdio: 'pipe',
      encoding: 'utf-8',
    });
    console.log(output);
    console.log('✅ D1 migrations applied');
  } catch (err) {
    // execSync throws on non-zero exit but wrangler may still succeed
    // Check if the output contains success indicators
    const combined = (err.stdout || '') + (err.stderr || '');
    if (combined.includes('✅') || combined.includes('executed successfully')) {
      console.log(combined);
      console.log('✅ D1 migrations applied');
    } else {
      console.error('❌ Failed to apply D1 migrations');
      console.error(combined);
      process.exit(1);
    }
  }
}
