/**
 * avatarImages — Platform-specific avatar image registries (native: PNG)
 *
 * Native platforms use full-size 2048px raw PNGs and 512px badge PNGs.
 * See avatarImages.web.ts for the web variant (512px + 128px WebP).
 */
import type { HandDrawnAvatarId } from '@werewolf/game-engine/growth/rewardCatalog';

// prettier-ignore
export const AVATAR_IMAGE_MAP: Record<HandDrawnAvatarId, number> = {
  avenger: require('../../assets/avatars/raw/avenger.png'),
  awakenedGargoyle: require('../../assets/avatars/raw/awakenedGargoyle.png'),
  bloodMoon: require('../../assets/avatars/raw/bloodMoon.png'),
  crow: require('../../assets/avatars/raw/crow.png'),
  cursedFox: require('../../assets/avatars/raw/cursedFox.png'),
  cupid: require('../../assets/avatars/raw/cupid.png'),
  dancer: require('../../assets/avatars/raw/dancer.png'),
  darkWolfKing: require('../../assets/avatars/raw/darkWolfKing.png'),
  dreamcatcher: require('../../assets/avatars/raw/dreamcatcher.png'),
  drunkSeer: require('../../assets/avatars/raw/drunkSeer.png'),
  gargoyle: require('../../assets/avatars/raw/gargoyle.png'),
  graveyardKeeper: require('../../assets/avatars/raw/graveyardKeeper.png'),
  guard: require('../../assets/avatars/raw/guard.png'),
  hunter: require('../../assets/avatars/raw/hunter.png'),
  idiot: require('../../assets/avatars/raw/idiot.png'),
  knight: require('../../assets/avatars/raw/knight.png'),
  magician: require('../../assets/avatars/raw/magician.png'),
  maskedMan: require('../../assets/avatars/raw/maskedMan.png'),
  masquerade: require('../../assets/avatars/raw/masquerade.png'),
  mirrorSeer: require('../../assets/avatars/raw/mirrorSeer.png'),
  nightmare: require('../../assets/avatars/raw/nightmare.png'),
  piper: require('../../assets/avatars/raw/piper.png'),
  poisoner: require('../../assets/avatars/raw/poisoner.png'),
  psychic: require('../../assets/avatars/raw/psychic.png'),
  pureWhite: require('../../assets/avatars/raw/pureWhite.png'),
  seer: require('../../assets/avatars/raw/seer.png'),
  shadow: require('../../assets/avatars/raw/shadow.png'),
  silenceElder: require('../../assets/avatars/raw/silenceElder.png'),
  slacker: require('../../assets/avatars/raw/slacker.png'),
  spiritKnight: require('../../assets/avatars/raw/spiritKnight.png'),
  thief: require('../../assets/avatars/raw/thief.png'),
  treasureMaster: require('../../assets/avatars/raw/treasureMaster.png'),
  villager: require('../../assets/avatars/raw/villager.png'),
  votebanElder: require('../../assets/avatars/raw/votebanElder.png'),
  warden: require('../../assets/avatars/raw/warden.png'),
  wildChild: require('../../assets/avatars/raw/wildChild.png'),
  witch: require('../../assets/avatars/raw/witch.png'),
  witcher: require('../../assets/avatars/raw/witcher.png'),
  wolf: require('../../assets/avatars/raw/wolf.png'),
  wolfKing: require('../../assets/avatars/raw/wolfKing.png'),
  wolfQueen: require('../../assets/avatars/raw/wolfQueen.png'),
  wolfRobot: require('../../assets/avatars/raw/wolfRobot.png'),
  wolfWitch: require('../../assets/avatars/raw/wolfWitch.png'),
};

// prettier-ignore
export const AVATAR_THUMB_MAP: Record<HandDrawnAvatarId, number> = {
  avenger: require('../../assets/badges/png/512/role_avenger.png'),
  awakenedGargoyle: require('../../assets/badges/png/512/role_awakenedGargoyle.png'),
  bloodMoon: require('../../assets/badges/png/512/role_bloodMoon.png'),
  crow: require('../../assets/badges/png/512/role_crow.png'),
  cursedFox: require('../../assets/badges/png/512/role_cursedFox.png'),
  cupid: require('../../assets/badges/png/512/role_cupid.png'),
  dancer: require('../../assets/badges/png/512/role_dancer.png'),
  darkWolfKing: require('../../assets/badges/png/512/role_darkWolfKing.png'),
  dreamcatcher: require('../../assets/badges/png/512/role_dreamcatcher.png'),
  drunkSeer: require('../../assets/badges/png/512/role_drunkSeer.png'),
  gargoyle: require('../../assets/badges/png/512/role_gargoyle.png'),
  graveyardKeeper: require('../../assets/badges/png/512/role_graveyardKeeper.png'),
  guard: require('../../assets/badges/png/512/role_guard.png'),
  hunter: require('../../assets/badges/png/512/role_hunter.png'),
  idiot: require('../../assets/badges/png/512/role_idiot.png'),
  knight: require('../../assets/badges/png/512/role_knight.png'),
  magician: require('../../assets/badges/png/512/role_magician.png'),
  maskedMan: require('../../assets/badges/png/512/role_maskedMan.png'),
  masquerade: require('../../assets/badges/png/512/role_masquerade.png'),
  mirrorSeer: require('../../assets/badges/png/512/role_mirrorSeer.png'),
  nightmare: require('../../assets/badges/png/512/role_nightmare.png'),
  piper: require('../../assets/badges/png/512/role_piper.png'),
  poisoner: require('../../assets/badges/png/512/role_poisoner.png'),
  psychic: require('../../assets/badges/png/512/role_psychic.png'),
  pureWhite: require('../../assets/badges/png/512/role_pureWhite.png'),
  seer: require('../../assets/badges/png/512/role_seer.png'),
  shadow: require('../../assets/badges/png/512/role_shadow.png'),
  silenceElder: require('../../assets/badges/png/512/role_silenceElder.png'),
  slacker: require('../../assets/badges/png/512/role_slacker.png'),
  spiritKnight: require('../../assets/badges/png/512/role_spiritKnight.png'),
  thief: require('../../assets/badges/png/512/role_thief.png'),
  treasureMaster: require('../../assets/badges/png/512/role_treasureMaster.png'),
  villager: require('../../assets/badges/png/512/role_villager.png'),
  votebanElder: require('../../assets/badges/png/512/role_votebanElder.png'),
  warden: require('../../assets/badges/png/512/role_warden.png'),
  wildChild: require('../../assets/badges/png/512/role_wildChild.png'),
  witch: require('../../assets/badges/png/512/role_witch.png'),
  witcher: require('../../assets/badges/png/512/role_witcher.png'),
  wolf: require('../../assets/badges/png/512/role_wolf.png'),
  wolfKing: require('../../assets/badges/png/512/role_wolfKing.png'),
  wolfQueen: require('../../assets/badges/png/512/role_wolfQueen.png'),
  wolfRobot: require('../../assets/badges/png/512/role_wolfRobot.png'),
  wolfWitch: require('../../assets/badges/png/512/role_wolfWitch.png'),
};
