/** Product reward catalog, collection queries, draw policy, and cosmetic reveal policy. */

export {
  AVATAR_IDS,
  type AvatarId,
  type FlairId,
  FRAME_IDS,
  type FrameId,
  FREE_AVATAR_IDS,
  FREE_FLAIR_IDS,
  FREE_FRAME_IDS,
  FREE_NAME_STYLE_IDS,
  FREE_ROLE_REVEAL_EFFECT_IDS,
  FREE_SEAT_ANIMATION_IDS,
  getItemRarity,
  HAND_DRAWN_AVATAR_IDS,
  type HandDrawnAvatarId,
  LEGENDARY_FRAME_IDS,
  NAME_STYLE_IDS,
  type NameStyleId,
  RARITIES,
  type Rarity,
  REWARD_POOL,
  REWARD_POOL_BY_ID,
  REWARD_TYPES,
  type RewardItem,
  type RewardType,
  ROLE_REVEAL_EFFECT_IDS,
  type RoleRevealEffectId,
  SEAT_ANIMATION_IDS,
  SEAT_FLAIR_IDS,
  type SeatAnimationId,
  SHARD_COSTS,
  SHARD_VALUES,
  TOTAL_UNLOCKABLE_COUNT,
} from './catalog';
export { rollGoldenDraws, rollNormalDraws } from './earnings';
export {
  type DrawType,
  GOLDEN_RATES,
  NORMAL_RATES,
  PITY_THRESHOLD,
  rollRarity,
  selectReward,
} from './gacha';
export {
  parseResolvedRoleRevealAnimation,
  RANDOMIZABLE_ANIMATIONS,
  type ResolvedRoleRevealAnimation,
  resolveRandomAnimation,
  type RoleRevealAnimation,
} from './revealAnimation';
export {
  getUnlockedAvatars,
  getUnlockedFlairs,
  getUnlockedFrames,
  getUnlockedNameStyles,
  getUnlockedRoleRevealEffects,
  getUnlockedSeatAnimations,
  isFlairUnlocked,
  isFrameUnlocked,
  isNameStyleUnlocked,
  isRoleRevealEffectUnlocked,
  isSeatAnimationUnlocked,
  parseUnlockedRewardIds,
} from './unlocks';
